### ISSUE TITLE
No images have been pushed to docker hub for v1.6.2-build20250108

### ISSUE THREAD

**Issue by ElKiwos** [rancher/image-build-cni-plugins#87]
The build and release action for v1.6.2-build20250108 has failed during the **push-multiarch** step due to a TLS handshake timeout, which led to the situation that there is no image on docker hub with the tag **v1.6.2-build20250108**

This leads to errors with deployments referencing the images, like rke2-multus for example

**Comment by Lucky112** [comment]
For anyone facing this issue with rke2-multus, you can try and set previous cni tag in your values.yaml
```
cniplugins:
  image:
    tag: v1.6.0-build20241022
```

**Comment by AndrStnz** [comment]
With **rke2-cilium** you must use:
```   
portmapPlugin:
   image:
    repository: "rancher/hardened-cni-plugins"
     tag: "v1.6.0-build20241022"
```
